/**
 * Grammar points of the 2025 HSK syllabus (《HSK 考试大纲（词汇、汉字、语法）》,
 * 中外语言交流合作中心, published 2025-11, in force 2026-07), grammar section,
 * printed pages 307–328. 593 points: HSK 1 70 · 2 78 · 3 96 · 4 95 · 5 70 ·
 * 6 50 · 7–9 134.
 *
 * Generated from the GitHub transcription krmanik/HSK-3.0 ("New HSK (2025)/HSK
 * Grammar"), checked page by page against the official PDF (three errors
 * fixed). The syllabus has no numbers, so ids are ours: H25-<level>-<nnn>
 * (level 79 = 7–9), in syllabus order. Superscripts (了¹/了²) are the
 * syllabus's own sense numbers.
 *
 * `families`: the label codes the point belongs to — the first is where it is
 * counted, the others also list it. Agreed with the site owner 2026-10-07.
 * Regenerate with the scripts in "Claude outputs/hsk2025/" rather than
 * editing by hand.
 */

export interface GrammarPoint {
  id: string;
  /** '1'–'6' or '7-9' */
  level: string;
  /** Printed page in the syllabus. */
  page: number;
  /** 类别 · 类别名称 · 细目 (any can be ''). */
  cat: string;
  sub: string;
  item: string;
  /** 语法内容 ('' for a few rows that only have a 细目). */
  text: string;
  families: string[];
}

export const HSK_SYLLABUS = 'HSK 2025';

export const HSK_GRAMMAR_2025: GrammarPoint[] = [
  {"id": "H25-1-001", "level": "1", "page": 308, "cat": "语素", "sub": "前缀", "item": "", "text": "小—、第—", "families": ["GRAM.AFFIX"]},
  {"id": "H25-1-002", "level": "1", "page": 308, "cat": "语素", "sub": "后缀", "item": "", "text": "—们、—边", "families": ["GRAM.AFFIX", "GRAM.LOCATIVE"]},
  {"id": "H25-1-003", "level": "1", "page": 308, "cat": "词类", "sub": "名词", "item": "方位名词", "text": "上、下、里、外、前、后", "families": ["GRAM.LOCATIVE"]},
  {"id": "H25-1-004", "level": "1", "page": 308, "cat": "词类", "sub": "动词", "item": "能愿动词", "text": "会、能", "families": ["GRAM.MODAL"]},
  {"id": "H25-1-005", "level": "1", "page": 308, "cat": "词类", "sub": "动词", "item": "能愿动词", "text": "想、要", "families": ["GRAM.MODAL"]},
  {"id": "H25-1-006", "level": "1", "page": 308, "cat": "词类", "sub": "动词", "item": "能愿动词", "text": "可以", "families": ["GRAM.MODAL"]},
  {"id": "H25-1-007", "level": "1", "page": 308, "cat": "词类", "sub": "动词", "item": "离合词", "text": "看病、睡觉、说话、上课、下课、上班、下班、生病", "families": ["VOC.SEPARABLE"]},
  {"id": "H25-1-008", "level": "1", "page": 308, "cat": "词类", "sub": "代词", "item": "疑问代词", "text": "多、多少、几、哪、哪儿、哪里、哪些、什么、谁、怎么、怎么样", "families": ["GRAM.QUESTION", "GRAM.PRON"]},
  {"id": "H25-1-009", "level": "1", "page": 308, "cat": "词类", "sub": "代词", "item": "人称代词", "text": "我、你、您、他、她、我们、你们、他们、她们、它、它们、大家", "families": ["GRAM.PRON"]},
  {"id": "H25-1-010", "level": "1", "page": 308, "cat": "词类", "sub": "代词", "item": "指示代词", "text": "这、那、这儿、那儿、这里、那里、这些、那些、有的、这个、那个、有些", "families": ["GRAM.PRON"]},
  {"id": "H25-1-011", "level": "1", "page": 308, "cat": "词类", "sub": "数词", "item": "", "text": "一、二/两、三、四、五、六、七、八、九、零、十、百、半、千", "families": ["GRAM.NUM"]},
  {"id": "H25-1-012", "level": "1", "page": 308, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（1）专用名量词：本、个、家、口、块、件、只、元", "families": ["VOC.MEASURE"]},
  {"id": "H25-1-013", "level": "1", "page": 308, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（2）借用名量词：杯", "families": ["VOC.MEASURE"]},
  {"id": "H25-1-014", "level": "1", "page": 308, "cat": "词类", "sub": "量词", "item": "时量词", "text": "日、号、岁、点、分、年、天", "families": ["VOC.MEASURE"]},
  {"id": "H25-1-015", "level": "1", "page": 308, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "非常、很、太、真、有（一）点儿", "families": ["GRAM.ADV"]},
  {"id": "H25-1-016", "level": "1", "page": 308, "cat": "词类", "sub": "副词", "item": "范围副词", "text": "都¹", "families": ["GRAM.ADV"]},
  {"id": "H25-1-017", "level": "1", "page": 308, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "在、正在", "families": ["GRAM.ADV", "GRAM.PROG"]},
  {"id": "H25-1-018", "level": "1", "page": 308, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "再¹", "families": ["GRAM.ADV"]},
  {"id": "H25-1-019", "level": "1", "page": 308, "cat": "词类", "sub": "副词", "item": "关联副词", "text": "还¹、也", "families": ["GRAM.ADV"]},
  {"id": "H25-1-020", "level": "1", "page": 308, "cat": "词类", "sub": "副词", "item": "否定副词", "text": "不、没（有）、不要", "families": ["GRAM.NEG"]},
  {"id": "H25-1-021", "level": "1", "page": 308, "cat": "词类", "sub": "介词", "item": "引出时间、处所", "text": "在", "families": ["GRAM.PREP"]},
  {"id": "H25-1-022", "level": "1", "page": 308, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "和¹、对", "families": ["GRAM.PREP"]},
  {"id": "H25-1-023", "level": "1", "page": 308, "cat": "词类", "sub": "连词", "item": "连接词语或短语", "text": "和²", "families": ["GRAM.CONJ"]},
  {"id": "H25-1-024", "level": "1", "page": 308, "cat": "词类", "sub": "助词", "item": "结构助词", "text": "的¹", "families": ["GRAM.DE"]},
  {"id": "H25-1-025", "level": "1", "page": 308, "cat": "词类", "sub": "助词", "item": "动态助词", "text": "了¹", "families": ["GRAM.LE"]},
  {"id": "H25-1-026", "level": "1", "page": 308, "cat": "词类", "sub": "助词", "item": "语气助词", "text": "吧¹、了²、吗、呢¹、呢²、呢³", "families": ["GRAM.PARTICLE", "GRAM.LE", "GRAM.QUESTION"]},
  {"id": "H25-1-027", "level": "1", "page": 308, "cat": "词类", "sub": "叹词", "item": "", "text": "喂", "families": ["GRAM.OTHER"]},
  {"id": "H25-1-028", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "基本结构类型", "text": "（1）联合短语", "families": ["GRAM.PHRASE"]},
  {"id": "H25-1-029", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "基本结构类型", "text": "（2）偏正短语", "families": ["GRAM.PHRASE"]},
  {"id": "H25-1-030", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "基本结构类型", "text": "（3）动宾短语", "families": ["GRAM.PHRASE"]},
  {"id": "H25-1-031", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "基本结构类型", "text": "（4）主谓短语", "families": ["GRAM.PHRASE"]},
  {"id": "H25-1-032", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "（1）数量短语", "families": ["VOC.MEASURE", "GRAM.NUM"]},
  {"id": "H25-1-033", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "（2）介宾短语", "families": ["GRAM.PREP"]},
  {"id": "H25-1-034", "level": "1", "page": 309, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "（3）方位短语", "families": ["GRAM.LOCATIVE"]},
  {"id": "H25-1-035", "level": "1", "page": 309, "cat": "句子成分", "sub": "主语", "item": "", "text": "名词、代词或名词性短语作主语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-036", "level": "1", "page": 309, "cat": "句子成分", "sub": "谓语", "item": "", "text": "名词、代词、数词或数量短语作谓语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-037", "level": "1", "page": 309, "cat": "句子成分", "sub": "谓语", "item": "", "text": "动词或动词性短语、形容词或形容词性短语作谓语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-038", "level": "1", "page": 309, "cat": "句子成分", "sub": "宾语", "item": "", "text": "名词、代词或名词性短语作宾语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-039", "level": "1", "page": 309, "cat": "句子成分", "sub": "定语", "item": "", "text": "名词性词语、形容词性短语、数量短语作定语", "families": ["GRAM.DE", "GRAM.ORDER"]},
  {"id": "H25-1-040", "level": "1", "page": 309, "cat": "句子成分", "sub": "状语", "item": "", "text": "副词、形容词作状语表示时间、处所的词语作状语", "families": ["GRAM.ORDER"]},
  {"id": "H25-1-041", "level": "1", "page": 309, "cat": "句子成分", "sub": "补语", "item": "数量补语1", "text": "动词+动量补语", "families": ["GRAM.COMP"]},
  {"id": "H25-1-042", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句型", "item": "单句", "text": "主谓句1：动词谓语句", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-043", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句型", "item": "单句", "text": "主谓句2：形容词谓语句", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-044", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句型", "item": "单句", "text": "主谓句3：名词谓语句", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-045", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句型", "item": "单句", "text": "非主谓句", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-1-046", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句类", "item": "陈述句", "text": "", "families": ["GRAM.OTHER"]},
  {"id": "H25-1-047", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句类", "item": "疑问句", "text": "（1）是非问句", "families": ["GRAM.QUESTION"]},
  {"id": "H25-1-048", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句类", "item": "疑问句", "text": "（2）特指问句", "families": ["GRAM.QUESTION"]},
  {"id": "H25-1-049", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句类", "item": "疑问句", "text": "（3）正反问句", "families": ["GRAM.QUESTION"]},
  {"id": "H25-1-050", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句类", "item": "祈使句", "text": "", "families": ["GRAM.OTHER"]},
  {"id": "H25-1-051", "level": "1", "page": 309, "cat": "句子的类型", "sub": "句类", "item": "感叹句", "text": "", "families": ["GRAM.OTHER"]},
  {"id": "H25-1-052", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "“是”字句1", "text": "表示等同或类属", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-1-053", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "“有”字句1", "text": "表示领有", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-1-054", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "存现句1", "text": "（1）所处+是+名词", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-1-055", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "存现句1", "text": "（2）处所+有+数量短语+名词", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-1-056", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "连动句1", "text": "（1）前后动作先后发生，后一动作是前一动作的目的", "families": ["GRAM.SERIAL"]},
  {"id": "H25-1-057", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "连动句1", "text": "（2）前一动作是后一动作的方式", "families": ["GRAM.SERIAL"]},
  {"id": "H25-1-058", "level": "1", "page": 309, "cat": "句子的类型", "sub": "特殊句型", "item": "双宾语句1", "text": "主语+动词+宾语1+宾语2", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-1-059", "level": "1", "page": 310, "cat": "句子的类型", "sub": "复句", "item": "不用关联词语的复句", "text": "", "families": ["GRAM.CONJ"]},
  {"id": "H25-1-060", "level": "1", "page": 310, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "……，也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-1-061", "level": "1", "page": 310, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "……，还……", "families": ["GRAM.CONJ"]},
  {"id": "H25-1-062", "level": "1", "page": 310, "cat": "动作的态", "sub": "", "item": "完成态", "text": "用动态助词“了¹”表示", "families": ["GRAM.LE"]},
  {"id": "H25-1-063", "level": "1", "page": 310, "cat": "动作的态", "sub": "", "item": "变化态", "text": "用动态助词“了²”表示", "families": ["GRAM.LE"]},
  {"id": "H25-1-064", "level": "1", "page": 310, "cat": "动作的态", "sub": "", "item": "进行态", "text": "（1）……在/正在+动词", "families": ["GRAM.PROG"]},
  {"id": "H25-1-065", "level": "1", "page": 310, "cat": "动作的态", "sub": "", "item": "进行态", "text": "（2）……在/正在+动词……+呢", "families": ["GRAM.PROG"]},
  {"id": "H25-1-066", "level": "1", "page": 310, "cat": "动作的态", "sub": "", "item": "进行态", "text": "（3）……呢", "families": ["GRAM.PROG"]},
  {"id": "H25-1-067", "level": "1", "page": 310, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "钱数表示法", "families": ["GRAM.NUM"]},
  {"id": "H25-1-068", "level": "1", "page": 310, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "序数表达法1：第+数词", "families": ["GRAM.NUM"]},
  {"id": "H25-1-069", "level": "1", "page": 310, "cat": "特殊表达法", "sub": "时间表示法", "item": "", "text": "（1）年、月、日、星期表示法", "families": ["GRAM.NUM"]},
  {"id": "H25-1-070", "level": "1", "page": 310, "cat": "特殊表达法", "sub": "时间表示法", "item": "", "text": "（2）钟点表示法", "families": ["GRAM.NUM"]},
  {"id": "H25-2-001", "level": "2", "page": 311, "cat": "语素", "sub": "后缀", "item": "", "text": "面", "families": ["GRAM.LOCATIVE", "GRAM.AFFIX"]},
  {"id": "H25-2-002", "level": "2", "page": 311, "cat": "词类", "sub": "名词", "item": "方位名词", "text": "左、右", "families": ["GRAM.LOCATIVE"]},
  {"id": "H25-2-003", "level": "2", "page": 311, "cat": "词类", "sub": "动词", "item": "动词重叠", "text": "AA、A一A、A了A、ABAB", "families": ["GRAM.REDUP"]},
  {"id": "H25-2-004", "level": "2", "page": 311, "cat": "词类", "sub": "动词", "item": "能愿动词", "text": "可能", "families": ["GRAM.MODAL"]},
  {"id": "H25-2-005", "level": "2", "page": 311, "cat": "词类", "sub": "动词", "item": "离合词", "text": "帮忙、游泳、跳舞、跑步", "families": ["VOC.SEPARABLE"]},
  {"id": "H25-2-006", "level": "2", "page": 311, "cat": "词类", "sub": "代词", "item": "疑问代词", "text": "为什么", "families": ["GRAM.QUESTION", "GRAM.PRON"]},
  {"id": "H25-2-007", "level": "2", "page": 311, "cat": "词类", "sub": "代词", "item": "人称代词", "text": "自己", "families": ["GRAM.PRON"]},
  {"id": "H25-2-008", "level": "2", "page": 311, "cat": "词类", "sub": "代词", "item": "指示代词", "text": "那么、那样、这么、这样、每", "families": ["GRAM.PRON"]},
  {"id": "H25-2-009", "level": "2", "page": 311, "cat": "词类", "sub": "形容词", "item": "形容词重叠", "text": "AA、AABB", "families": ["GRAM.REDUP"]},
  {"id": "H25-2-010", "level": "2", "page": 311, "cat": "词类", "sub": "数词", "item": "", "text": "万、好多、多", "families": ["GRAM.NUM"]},
  {"id": "H25-2-011", "level": "2", "page": 311, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（1）专用名量词：条、位、间、名", "families": ["VOC.MEASURE"]},
  {"id": "H25-2-012", "level": "2", "page": 311, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（2）借用名量词：包", "families": ["VOC.MEASURE"]},
  {"id": "H25-2-013", "level": "2", "page": 311, "cat": "词类", "sub": "量词", "item": "动量词", "text": "次", "families": ["VOC.MEASURE"]},
  {"id": "H25-2-014", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "多、好、最", "families": ["GRAM.ADV"]},
  {"id": "H25-2-015", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "范围副词", "text": "一起", "families": ["GRAM.ADV"]},
  {"id": "H25-2-016", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "还²、已经、有时（候）、快、快要、正", "families": ["GRAM.ADV"]},
  {"id": "H25-2-017", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "常、经常", "families": ["GRAM.ADV"]},
  {"id": "H25-2-018", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "否定副词", "text": "别", "families": ["GRAM.NEG"]},
  {"id": "H25-2-019", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "关联副词", "text": "再²、就¹", "families": ["GRAM.ADV"]},
  {"id": "H25-2-020", "level": "2", "page": 311, "cat": "词类", "sub": "副词", "item": "语气副词", "text": "都²、就²、还是¹", "families": ["GRAM.ADV"]},
  {"id": "H25-2-021", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出时间、处所", "text": "从¹", "families": ["GRAM.PREP"]},
  {"id": "H25-2-022", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出方向、路径", "text": "往", "families": ["GRAM.PREP"]},
  {"id": "H25-2-023", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出方向、路径", "text": "从²", "families": ["GRAM.PREP"]},
  {"id": "H25-2-024", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "给", "families": ["GRAM.PREP"]},
  {"id": "H25-2-025", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "比", "families": ["GRAM.COMPAR", "GRAM.PREP"]},
  {"id": "H25-2-026", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "跟¹", "families": ["GRAM.PREP"]},
  {"id": "H25-2-027", "level": "2", "page": 311, "cat": "词类", "sub": "介词", "item": "引出原因", "text": "因为¹", "families": ["GRAM.PREP"]},
  {"id": "H25-2-028", "level": "2", "page": 311, "cat": "词类", "sub": "连词", "item": "连接词或短语", "text": "跟²", "families": ["GRAM.CONJ"]},
  {"id": "H25-2-029", "level": "2", "page": 311, "cat": "词类", "sub": "连词", "item": "连接分句或者句子", "text": "但、但是、那、虽然、还是²、因为²、所以", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-2-030", "level": "2", "page": 311, "cat": "词类", "sub": "助词", "item": "结构助词", "text": "得、地", "families": ["GRAM.DE"]},
  {"id": "H25-2-031", "level": "2", "page": 311, "cat": "词类", "sub": "助词", "item": "动态助词", "text": "过", "families": ["GRAM.GUOZHE"]},
  {"id": "H25-2-032", "level": "2", "page": 311, "cat": "词类", "sub": "助词", "item": "动态助词", "text": "着", "families": ["GRAM.GUOZHE"]},
  {"id": "H25-2-033", "level": "2", "page": 311, "cat": "词类", "sub": "助词", "item": "语气助词", "text": "呢⁴、吧²、的²、啊¹", "families": ["GRAM.PARTICLE"]},
  {"id": "H25-2-034", "level": "2", "page": 311, "cat": "短语", "sub": "结构类型", "item": "基本结构类型", "text": "动补短语1", "families": ["GRAM.COMP"]},
  {"id": "H25-2-035", "level": "2", "page": 312, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "（1）“的”字短语", "families": ["GRAM.DE"]},
  {"id": "H25-2-036", "level": "2", "page": 312, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "（2）连谓短语", "families": ["GRAM.SERIAL"]},
  {"id": "H25-2-037", "level": "2", "page": 312, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "（3）兼语短语", "families": ["GRAM.SERIAL"]},
  {"id": "H25-2-038", "level": "2", "page": 312, "cat": "短语", "sub": "功能类型", "item": "名词性短语", "text": "", "families": ["GRAM.PHRASE"]},
  {"id": "H25-2-039", "level": "2", "page": 312, "cat": "短语", "sub": "功能类型", "item": "动词性短语", "text": "", "families": ["GRAM.PHRASE"]},
  {"id": "H25-2-040", "level": "2", "page": 312, "cat": "短语", "sub": "功能类型", "item": "形容词性短语", "text": "", "families": ["GRAM.PHRASE"]},
  {"id": "H25-2-041", "level": "2", "page": 312, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "什么的", "families": ["GRAM.FIXED"]},
  {"id": "H25-2-042", "level": "2", "page": 312, "cat": "固定格式", "sub": "", "item": "", "text": "还是……吧", "families": ["GRAM.FIXED", "GRAM.PARTICLE"]},
  {"id": "H25-2-043", "level": "2", "page": 312, "cat": "固定格式", "sub": "", "item": "", "text": "要/快要/就要……了", "families": ["GRAM.LE", "GRAM.FIXED"]},
  {"id": "H25-2-044", "level": "2", "page": 312, "cat": "固定格式", "sub": "", "item": "", "text": "都……了", "families": ["GRAM.LE", "GRAM.FIXED"]},
  {"id": "H25-2-045", "level": "2", "page": 312, "cat": "句子成分", "sub": "主语", "item": "", "text": "受事主语", "families": ["GRAM.BEI", "GRAM.CONSTIT"]},
  {"id": "H25-2-046", "level": "2", "page": 312, "cat": "句子成分", "sub": "谓语", "item": "", "text": "名词性短语作谓语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-2-047", "level": "2", "page": 312, "cat": "句子成分", "sub": "定语", "item": "", "text": "动词或动词性短语、主谓短语作定语", "families": ["GRAM.DE", "GRAM.ORDER"]},
  {"id": "H25-2-048", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "结果补语1", "text": "动词+错/懂/好/会/完", "families": ["GRAM.COMP"]},
  {"id": "H25-2-049", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "趋向补语1", "text": "简单趋向补语的趋向意义用法：（1）动词+来/去", "families": ["GRAM.COMP"]},
  {"id": "H25-2-050", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "趋向补语1", "text": "（2）动词+上/下/进/出/过/回", "families": ["GRAM.COMP"]},
  {"id": "H25-2-051", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "趋向补语1", "text": "复合趋向补语的趋向意义用法：动词+出来/出去/过来/过去/回来/回去/进来/进去/起来/上来/上去/下来/下去", "families": ["GRAM.COMP"]},
  {"id": "H25-2-052", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "状态补语1", "text": "动词+得+形容词性短语", "families": ["GRAM.COMP", "GRAM.DE"]},
  {"id": "H25-2-053", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "数量补语2", "text": "（1）表示动作持续的时间", "families": ["GRAM.COMP"]},
  {"id": "H25-2-054", "level": "2", "page": 312, "cat": "句子成分", "sub": "补语", "item": "数量补语2", "text": "（2）形容词+数量补语", "families": ["GRAM.COMP"]},
  {"id": "H25-2-055", "level": "2", "page": 312, "cat": "句子的类型", "sub": "句型", "item": "单句", "text": "主谓句4：主谓谓语句", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-2-056", "level": "2", "page": 312, "cat": "句子的类型", "sub": "句类", "item": "疑问句", "text": "用“还是”连接的选择问句", "families": ["GRAM.QUESTION"]},
  {"id": "H25-2-057", "level": "2", "page": 312, "cat": "句子的类型", "sub": "句类", "item": "祈使句", "text": "用“别”的祈使句", "families": ["GRAM.NEG"]},
  {"id": "H25-2-058", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "“是”字句2", "text": "表示说明或特征", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-2-059", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "“有”字句2", "text": "表示达到", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-2-060", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "存现句2", "text": "处所+动词+着(+数量短语)+名词", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-2-061", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "比较句1", "text": "（1）A比B+形容词", "families": ["GRAM.COMPAR"]},
  {"id": "H25-2-062", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "比较句1", "text": "（2）A比B+形容词+数量补语/程度补语", "families": ["GRAM.COMPAR"]},
  {"id": "H25-2-063", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "比较句1", "text": "（3）A有/没有B（+这么/那么）+形容词", "families": ["GRAM.COMPAR"]},
  {"id": "H25-2-064", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "比较句1", "text": "（4）A比B+动词+得+形容词/A+动词+得+比+B+形容词", "families": ["GRAM.COMPAR"]},
  {"id": "H25-2-065", "level": "2", "page": 312, "cat": "句子的类型", "sub": "特殊句式", "item": "“是……的”句1", "text": "强调时间、地点、方式、动作者", "families": ["GRAM.SHIDE"]},
  {"id": "H25-2-066", "level": "2", "page": 313, "cat": "句子的类型", "sub": "特殊句式", "item": "兼语句1", "text": "表使令：主语+请/叫/让……+宾语1+动词+宾语2", "families": ["GRAM.SERIAL"]},
  {"id": "H25-2-067", "level": "2", "page": 313, "cat": "句子的类型", "sub": "特殊句式", "item": "双宾语句2", "text": "主语+动词+给+宾语1+宾语2", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-2-068", "level": "2", "page": 313, "cat": "句子的类型", "sub": "复句", "item": "选择复句", "text": "（是）……，还是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-2-069", "level": "2", "page": 313, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "虽然……，但是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-2-070", "level": "2", "page": 313, "cat": "句子的类型", "sub": "复句", "item": "因果复句", "text": "因为……，所以……", "families": ["GRAM.CONJ"]},
  {"id": "H25-2-071", "level": "2", "page": 313, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "一……就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-2-072", "level": "2", "page": 313, "cat": "动作的态", "sub": "", "item": "持续态", "text": "动词+着：（1）表示状态的持续", "families": ["GRAM.GUOZHE"]},
  {"id": "H25-2-073", "level": "2", "page": 313, "cat": "动作的态", "sub": "", "item": "持续态", "text": "（2）表示动作的持续", "families": ["GRAM.GUOZHE"]},
  {"id": "H25-2-074", "level": "2", "page": 313, "cat": "动作的态", "sub": "", "item": "经历态", "text": "用动态助词“过”表示", "families": ["GRAM.GUOZHE"]},
  {"id": "H25-2-075", "level": "2", "page": 313, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "序数表示法2：数词+量词", "families": ["GRAM.NUM"]},
  {"id": "H25-2-076", "level": "2", "page": 313, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "概数表达法1：（1）用“几”表示概数", "families": ["GRAM.NUM"]},
  {"id": "H25-2-077", "level": "2", "page": 313, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "（2）数词+多+量词", "families": ["GRAM.NUM"]},
  {"id": "H25-2-078", "level": "2", "page": 313, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "（3）数词+量词+多", "families": ["GRAM.NUM"]},
  {"id": "H25-3-001", "level": "3", "page": 314, "cat": "语素", "sub": "前缀", "item": "", "text": "老—", "families": ["GRAM.AFFIX"]},
  {"id": "H25-3-002", "level": "3", "page": 314, "cat": "语素", "sub": "后缀", "item": "", "text": "—家、—子、—员", "families": ["GRAM.AFFIX"]},
  {"id": "H25-3-003", "level": "3", "page": 314, "cat": "词类", "sub": "名词", "item": "方位名词", "text": "东、南、西、北、北方、东方、南方、西方、中间", "families": ["GRAM.LOCATIVE"]},
  {"id": "H25-3-004", "level": "3", "page": 314, "cat": "词类", "sub": "动词", "item": "能愿动词", "text": "需要、该、应该、愿意、得", "families": ["GRAM.MODAL"]},
  {"id": "H25-3-005", "level": "3", "page": 314, "cat": "词类", "sub": "动词", "item": "离合词", "text": "动宾式离合词：放假、见面、结婚、洗澡", "families": ["VOC.SEPARABLE"]},
  {"id": "H25-3-006", "level": "3", "page": 314, "cat": "词类", "sub": "动词", "item": "离合词", "text": "动补式离合词：离开、完成、分开", "families": ["VOC.SEPARABLE"]},
  {"id": "H25-3-007", "level": "3", "page": 314, "cat": "词类", "sub": "代词", "item": "疑问代词", "text": "怎样", "families": ["GRAM.QUESTION", "GRAM.PRON"]},
  {"id": "H25-3-008", "level": "3", "page": 314, "cat": "词类", "sub": "代词", "item": "疑问代词", "text": "疑问代词的非疑问用法：（1）任指用法：①疑问代词+都……②疑问代词+疑问代词", "families": ["GRAM.QUESTION", "GRAM.PRON"]},
  {"id": "H25-3-009", "level": "3", "page": 314, "cat": "词类", "sub": "代词", "item": "疑问代词", "text": "（2）不定指用法", "families": ["GRAM.QUESTION", "GRAM.PRON"]},
  {"id": "H25-3-010", "level": "3", "page": 314, "cat": "词类", "sub": "代词", "item": "人称代词", "text": "别人、咱们", "families": ["GRAM.PRON"]},
  {"id": "H25-3-011", "level": "3", "page": 314, "cat": "词类", "sub": "代词", "item": "指示代词", "text": "别的、其他", "families": ["GRAM.PRON"]},
  {"id": "H25-3-012", "level": "3", "page": 314, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（1）专用名量词：把、双、张、种、层、封、页、辆、节、所、班、段、头、句、公斤、斤、角、毛、刻、米", "families": ["VOC.MEASURE"]},
  {"id": "H25-3-013", "level": "3", "page": 314, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（2）借用名量词：碗、盘", "families": ["VOC.MEASURE"]},
  {"id": "H25-3-014", "level": "3", "page": 314, "cat": "词类", "sub": "量词", "item": "动量词", "text": "口、回、遍、声", "families": ["VOC.MEASURE"]},
  {"id": "H25-3-015", "level": "3", "page": 314, "cat": "词类", "sub": "量词", "item": "量词重叠", "text": "个个、张张", "families": ["GRAM.REDUP", "VOC.MEASURE"]},
  {"id": "H25-3-016", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "比较、还³、更、特别、挺、有些、越、极", "families": ["GRAM.ADV"]},
  {"id": "H25-3-017", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "范围副词", "text": "就³、一块儿、一共、只、到处、只是", "families": ["GRAM.ADV"]},
  {"id": "H25-3-018", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "才¹、马上、先、一会儿、刚、刚刚、一直", "families": ["GRAM.ADV"]},
  {"id": "H25-3-019", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "总、总是、又、常常", "families": ["GRAM.ADV"]},
  {"id": "H25-3-020", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "关联副词", "text": "一边", "families": ["GRAM.ADV"]},
  {"id": "H25-3-021", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "情态副词", "text": "大概、必须、差不多、一定、好像、几乎", "families": ["GRAM.ADV"]},
  {"id": "H25-3-022", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "语气副词", "text": "当然、其实、终于、才²、才³、就⁴", "families": ["GRAM.ADV"]},
  {"id": "H25-3-023", "level": "3", "page": 314, "cat": "词类", "sub": "副词", "item": "否定副词", "text": "不必、不用", "families": ["GRAM.NEG"]},
  {"id": "H25-3-024", "level": "3", "page": 314, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "为¹、向¹、关于", "families": ["GRAM.PREP"]},
  {"id": "H25-3-025", "level": "3", "page": 314, "cat": "词类", "sub": "介词", "item": "引出方向、路径", "text": "向²", "families": ["GRAM.PREP"]},
  {"id": "H25-3-026", "level": "3", "page": 314, "cat": "词类", "sub": "介词", "item": "引出目的、原因", "text": "为了、为²", "families": ["GRAM.PREP"]},
  {"id": "H25-3-027", "level": "3", "page": 314, "cat": "词类", "sub": "介词", "item": "引出施事、受事", "text": "把、被", "families": ["GRAM.BA", "GRAM.BEI"]},
  {"id": "H25-3-028", "level": "3", "page": 314, "cat": "词类", "sub": "介词", "item": "引出凭借、依据", "text": "根据", "families": ["GRAM.PREP"]},
  {"id": "H25-3-029", "level": "3", "page": 314, "cat": "词类", "sub": "连词", "item": "连接词或者短语", "text": "或、或者", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-030", "level": "3", "page": 314, "cat": "词类", "sub": "连词", "item": "连接分句或句子", "text": "只有、只要、不但、而且、如果、可¹、可是、然后", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-3-031", "level": "3", "page": 314, "cat": "词类", "sub": "助词", "item": "其他助词", "text": "的话", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-032", "level": "3", "page": 315, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "同位短语", "families": ["GRAM.PHRASE"]},
  {"id": "H25-3-033", "level": "3", "page": 315, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "动补短语2", "families": ["GRAM.COMP"]},
  {"id": "H25-3-034", "level": "3", "page": 315, "cat": "短语", "sub": "结构类型", "item": "其他结构类型", "text": "数量重叠：数词+量词+数词+量词", "families": ["GRAM.REDUP", "VOC.MEASURE"]},
  {"id": "H25-3-035", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "不A不B", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-036", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "不一会儿", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-037", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "看来", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-038", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "在……看来", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-039", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "越来越", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-040", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "看起来", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-041", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "看上去", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-042", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "一般来说", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-043", "level": "3", "page": 315, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "不怎么样", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-044", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "除了 ……（以外），……还/也/都……", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-045", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "从……起", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-3-046", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "对……来说", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-3-047", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "一……也/都+不/没……", "families": ["GRAM.NEG", "GRAM.FIXED"]},
  {"id": "H25-3-048", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "一点儿也不", "families": ["GRAM.NEG", "GRAM.FIXED"]},
  {"id": "H25-3-049", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "越……越……", "families": ["GRAM.FIXED"]},
  {"id": "H25-3-050", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "（在）……以前/以后/前/后", "families": ["GRAM.LOCATIVE", "GRAM.FIXED"]},
  {"id": "H25-3-051", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "X什么（啊）", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-3-052", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "该……了", "families": ["GRAM.LE", "GRAM.FIXED"]},
  {"id": "H25-3-053", "level": "3", "page": 315, "cat": "固定格式", "sub": "", "item": "", "text": "在……上/下/中", "families": ["GRAM.LOCATIVE", "GRAM.FIXED"]},
  {"id": "H25-3-054", "level": "3", "page": 315, "cat": "句子成分", "sub": "主语", "item": "", "text": "动词或动词性短语、形容词或形容词性短语作主语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-3-055", "level": "3", "page": 315, "cat": "句子成分", "sub": "主语", "item": "", "text": "主谓短语作主语", "families": ["GRAM.CONSTIT"]},
  {"id": "H25-3-056", "level": "3", "page": 315, "cat": "句子成分", "sub": "定语", "item": "", "text": "多项定语", "families": ["GRAM.ORDER", "GRAM.DE"]},
  {"id": "H25-3-057", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "结果补语2", "text": "动词+到/住/走/上", "families": ["GRAM.COMP"]},
  {"id": "H25-3-058", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "趋向补语2", "text": "趋向补语的引申用法：（1）表示结果意义：动词+出/起/下", "families": ["GRAM.COMP"]},
  {"id": "H25-3-059", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "趋向补语2", "text": "（2）表示动作行为的开始：动词+上/起来", "families": ["GRAM.COMP"]},
  {"id": "H25-3-060", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "趋向补语2", "text": "（3）表示动作行为的持续：动词+下去/下来", "families": ["GRAM.COMP"]},
  {"id": "H25-3-061", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "可能补语1", "text": "动词+得/不+动词/形容词", "families": ["GRAM.COMP"]},
  {"id": "H25-3-062", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "程度补语1", "text": "（1）形容词+得很", "families": ["GRAM.COMP", "GRAM.DE"]},
  {"id": "H25-3-063", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "程度补语1", "text": "（2）形容词/动词+极了/坏了", "families": ["GRAM.COMP"]},
  {"id": "H25-3-064", "level": "3", "page": 315, "cat": "句子成分", "sub": "补语", "item": "数量补语3", "text": "表示动作结束到某个时间点的间隔时间", "families": ["GRAM.COMP"]},
  {"id": "H25-3-065", "level": "3", "page": 316, "cat": "句子的类型", "sub": "句类", "item": "疑问句", "text": "“怎样+动词”的特指问句", "families": ["GRAM.QUESTION"]},
  {"id": "H25-3-066", "level": "3", "page": 316, "cat": "句子的类型", "sub": "句类", "item": "反问句1", "text": "用反问句表示强调：不是……吗？", "families": ["GRAM.QUESTION"]},
  {"id": "H25-3-067", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句1", "text": "（1）主语+把+宾语+动词+在/到+处所", "families": ["GRAM.BA"]},
  {"id": "H25-3-068", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句1", "text": "（2）主语+把+宾语1+动词（+给）+宾语2", "families": ["GRAM.BA"]},
  {"id": "H25-3-069", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句1", "text": "（3）主语+把+宾语+动词+结果补语/趋向补语/状态补语", "families": ["GRAM.BA"]},
  {"id": "H25-3-070", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "被动句1", "text": "（1）主语+被+宾语+动词+其他成分", "families": ["GRAM.BEI"]},
  {"id": "H25-3-071", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "被动句1", "text": "（2）主语+被+动词+其他成分", "families": ["GRAM.BEI"]},
  {"id": "H25-3-072", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "连动句2", "text": "“着”表示动作的伴随：动词1+着+动词2", "families": ["GRAM.SERIAL", "GRAM.GUOZHE"]},
  {"id": "H25-3-073", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句2", "text": "（1）A比B+更/还+形容词", "families": ["GRAM.COMPAR"]},
  {"id": "H25-3-074", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句2", "text": "（2）A跟B一样", "families": ["GRAM.COMPAR"]},
  {"id": "H25-3-075", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句2", "text": "（3）A跟B一样+形容词", "families": ["GRAM.COMPAR"]},
  {"id": "H25-3-076", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句2", "text": "（4）A不比B+形容词", "families": ["GRAM.COMPAR"]},
  {"id": "H25-3-077", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句2", "text": "（5）A比B+多/少/早/晚+动词+数量短语", "families": ["GRAM.COMPAR"]},
  {"id": "H25-3-078", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "存现句3", "text": "（1）表示出现：处所词+动词+趋向补语/结果补语+动态助词（了）+数量短语+人/物", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-3-079", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "存现句3", "text": "（2）表示消失：处所词+动词+结果补语+动态助词（了）+数量短语+人/物", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-3-080", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "“是……的”句2", "text": "强调说话人的看法或态度", "families": ["GRAM.SHIDE"]},
  {"id": "H25-3-081", "level": "3", "page": 316, "cat": "句子的类型", "sub": "特殊句型", "item": "重动句", "text": "主语+动词+宾语+动词+补语", "families": ["GRAM.COMP"]},
  {"id": "H25-3-082", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "承接复句", "text": "先……，再/然后……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-083", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "选择复句", "text": "或者……，或者……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-084", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "一会儿……，一会儿……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-085", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "又……，又……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-086", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "一边……，一边……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-087", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "不但……，而且……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-088", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "虽然……，可是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-089", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "如果……，就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-090", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "……的话，就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-091", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "只有……，才……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-092", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "只要……，就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-093", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "目的复句", "text": "为了……，……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-094", "level": "3", "page": 316, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "……了……（就）……", "families": ["GRAM.CONJ"]},
  {"id": "H25-3-095", "level": "3", "page": 316, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "概数表达法2：（1）用“大概”表示概数", "families": ["GRAM.NUM"]},
  {"id": "H25-3-096", "level": "3", "page": 316, "cat": "特殊表达法", "sub": "数的表达法", "item": "", "text": "（2）相邻数词连用表示概数", "families": ["GRAM.NUM"]},
  {"id": "H25-4-001", "level": "4", "page": 317, "cat": "词类", "sub": "动词", "item": "能愿动词", "text": "敢", "families": ["GRAM.MODAL"]},
  {"id": "H25-4-002", "level": "4", "page": 317, "cat": "词类", "sub": "代词", "item": "指示代词", "text": "各、各位、各种、任何、此", "families": ["GRAM.PRON"]},
  {"id": "H25-4-003", "level": "4", "page": 317, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（1）专用名量词：打、袋、棵、台、幅", "families": ["VOC.MEASURE"]},
  {"id": "H25-4-004", "level": "4", "page": 317, "cat": "词类", "sub": "量词", "item": "名量词", "text": "（2）借用名量词：脸、手、盒、屋子、桌子", "families": ["VOC.MEASURE"]},
  {"id": "H25-4-005", "level": "4", "page": 317, "cat": "词类", "sub": "量词", "item": "动量词", "text": "场、顿、趟", "families": ["VOC.MEASURE"]},
  {"id": "H25-4-006", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "十分、更加、稍、稍微、尤其、多么", "families": ["GRAM.ADV"]},
  {"id": "H25-4-007", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "范围副词", "text": "共、全、光、仅、仅仅、至少", "families": ["GRAM.ADV"]},
  {"id": "H25-4-008", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "按时、从来、赶紧、赶快、已、忽然、将、将要、从、本来", "families": ["GRAM.ADV"]},
  {"id": "H25-4-009", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "重新、往往、偶尔、再次、老", "families": ["GRAM.ADV"]},
  {"id": "H25-4-010", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "方式副词", "text": "故意、互相、相互", "families": ["GRAM.ADV"]},
  {"id": "H25-4-011", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "关联副词", "text": "却", "families": ["GRAM.ADV"]},
  {"id": "H25-4-012", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "情态副词", "text": "也许、恐怕", "families": ["GRAM.ADV"]},
  {"id": "H25-4-013", "level": "4", "page": 317, "cat": "词类", "sub": "副词", "item": "语气副词", "text": "才⁴、就⁵、并¹、还⁴、竟然、究竟、正好、到底、难道、千万、确实、只好、差（一）点儿", "families": ["GRAM.ADV"]},
  {"id": "H25-4-014", "level": "4", "page": 317, "cat": "词类", "sub": "介词", "item": "引出时间、处所", "text": "自、当、由¹、随着、等¹", "families": ["GRAM.PREP"]},
  {"id": "H25-4-015", "level": "4", "page": 317, "cat": "词类", "sub": "介词", "item": "引出施事、受事", "text": "将、由²、叫、让", "families": ["GRAM.BA", "GRAM.BEI"]},
  {"id": "H25-4-016", "level": "4", "page": 317, "cat": "词类", "sub": "介词", "item": "引出原因", "text": "由于¹", "families": ["GRAM.PREP"]},
  {"id": "H25-4-017", "level": "4", "page": 317, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "对于、与¹", "families": ["GRAM.PREP"]},
  {"id": "H25-4-018", "level": "4", "page": 317, "cat": "词类", "sub": "介词", "item": "引出凭借、依据", "text": "作为、按、按照", "families": ["GRAM.PREP"]},
  {"id": "H25-4-019", "level": "4", "page": 317, "cat": "词类", "sub": "连词", "item": "连接词或词组", "text": "并²、而¹、与²", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-020", "level": "4", "page": 317, "cat": "词类", "sub": "连词", "item": "连接分句或句子", "text": "此外、而²、既然、甚至、不过、并且", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-4-021", "level": "4", "page": 317, "cat": "词类", "sub": "连词", "item": "连接分句或句子", "text": "不光、不仅、另外、要是、因此、由于²、加上", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-4-022", "level": "4", "page": 317, "cat": "词类", "sub": "助词", "item": "其他助词", "text": "等²、者、之、就是", "families": ["GRAM.OTHER"]},
  {"id": "H25-4-023", "level": "4", "page": 317, "cat": "词类", "sub": "叹词", "item": "", "text": "啊、嗯", "families": ["GRAM.OTHER"]},
  {"id": "H25-4-024", "level": "4", "page": 317, "cat": "短语", "sub": "结构类型", "item": "", "text": "数词+形容词+量词", "families": ["VOC.MEASURE", "GRAM.NUM"]},
  {"id": "H25-4-025", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "一A一B", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-026", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "无A无B", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-027", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "有A有B", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-028", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "来得及/来不及", "families": ["GRAM.COMP", "GRAM.FIXED"]},
  {"id": "H25-4-029", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "有的是", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-030", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "说不定", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-031", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "不怎么", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-032", "level": "4", "page": 317, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "就是说/这就是说", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-033", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "一+量词+比+一+量词", "families": ["GRAM.COMPAR", "GRAM.FIXED"]},
  {"id": "H25-4-034", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "在……方面", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-4-035", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "够……的", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-036", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "拿……来说", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-4-037", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "再也不/没……", "families": ["GRAM.NEG", "GRAM.FIXED"]},
  {"id": "H25-4-038", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "怎么都/也+不/没……", "families": ["GRAM.NEG", "GRAM.FIXED"]},
  {"id": "H25-4-039", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "为了……而……", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-4-040", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "动词+一X是一X", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-041", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "（没）有什么（好）X的", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-4-042", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "X是X，Y是Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-043", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "X也得X，不X也得X", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-044", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "X就是了", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-045", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "还X呢", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-046", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "你X你的吧", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-047", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "让/叫你X你就X", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-048", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "说什么/怎么（着）也得X", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-4-049", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "X就X（点儿）吧", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-050", "level": "4", "page": 318, "cat": "固定格式", "sub": "", "item": "", "text": "X是X", "families": ["GRAM.FIXED"]},
  {"id": "H25-4-051", "level": "4", "page": 318, "cat": "句子成分", "sub": "", "item": "程度补语2", "text": "形容词/心理动词+死了/厉害", "families": ["GRAM.COMP"]},
  {"id": "H25-4-052", "level": "4", "page": 318, "cat": "句子成分", "sub": "", "item": "可能补语2", "text": "动词+得/不+了", "families": ["GRAM.COMP"]},
  {"id": "H25-4-053", "level": "4", "page": 318, "cat": "句子的类型", "sub": "句类", "item": "反问句2", "text": "难道……吗？", "families": ["GRAM.QUESTION"]},
  {"id": "H25-4-054", "level": "4", "page": 318, "cat": "句子的类型", "sub": "句类", "item": "反问句2", "text": "由疑问代词构成的反问句", "families": ["GRAM.QUESTION"]},
  {"id": "H25-4-055", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句2", "text": "（1）主语+把+宾语+动词（+一/了）+动词", "families": ["GRAM.BA"]},
  {"id": "H25-4-056", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句2", "text": "（2）主语+把+宾语+动词+了", "families": ["GRAM.BA"]},
  {"id": "H25-4-057", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句2", "text": "（3）主语+把+宾语+动词+动量补语/时量补语", "families": ["GRAM.BA"]},
  {"id": "H25-4-058", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句2", "text": "（4）主语+把+宾语+状语+动词", "families": ["GRAM.BA"]},
  {"id": "H25-4-059", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "被动句2", "text": "主语+叫/让+宾语+动词+其他成分", "families": ["GRAM.BEI"]},
  {"id": "H25-4-060", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "兼语句2", "text": "（1）表爱憎义：主语+表扬/批评+宾语1+动词+宾语2", "families": ["GRAM.SERIAL"]},
  {"id": "H25-4-061", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "兼语句2", "text": "（2）表称谓或认定义：主语+收/选+宾语1+做/当/为+宾语2", "families": ["GRAM.SERIAL"]},
  {"id": "H25-4-062", "level": "4", "page": 318, "cat": "句子的类型", "sub": "特殊句型", "item": "兼语句2", "text": "（3）表致使：主语+使/让+人称代词+动词短语", "families": ["GRAM.SERIAL"]},
  {"id": "H25-4-063", "level": "4", "page": 319, "cat": "句子的类型", "sub": "", "item": "比较句3", "text": "（1）A不如B（+形容词）", "families": ["GRAM.COMPAR"]},
  {"id": "H25-4-064", "level": "4", "page": 319, "cat": "句子的类型", "sub": "", "item": "比较句3", "text": "（2）跟……相比", "families": ["GRAM.COMPAR"]},
  {"id": "H25-4-065", "level": "4", "page": 319, "cat": "句子的类型", "sub": "", "item": "双重否定句", "text": "用双重否定表示强调", "families": ["GRAM.NEG"]},
  {"id": "H25-4-066", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "不是……，而是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-067", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "既……，又/也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-068", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "一方面……，另一方面……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-069", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "承接复句", "text": "首先……，其次……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-070", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "承接复句", "text": "首先……，然后……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-071", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "承接复句", "text": "……，于是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-072", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "……，甚至……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-073", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "不仅/不光……，还/而且……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-074", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "……，并且……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-075", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "连……也/都……，……更……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-076", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "选择复句", "text": "不是……，就是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-077", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "尽管……，但是/可是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-078", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "……，然而……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-079", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "……，不过……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-080", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "……X是X，就是/不过……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-081", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "……，否则……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-082", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "要是……，就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-083", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "要是……，（就）……，否则……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-084", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "不管……，都/也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-085", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "无论……，都/也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-086", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "因果复句", "text": "既然……，就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-087", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "因果复句", "text": "（由于）……，因此……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-088", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "目的复句", "text": "……，好……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-089", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "让步复句", "text": "即使……，也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-090", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "让步复句", "text": "就是……，也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-091", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "无标记", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-092", "level": "4", "page": 319, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "不……也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-4-093", "level": "4", "page": 319, "cat": "特殊表达法", "sub": "数的表示法", "item": "", "text": "概数表示法3：数词+来+量词", "families": ["GRAM.NUM"]},
  {"id": "H25-4-094", "level": "4", "page": 319, "cat": "特殊表达法", "sub": "数的表示法", "item": "", "text": "用“大约、左右、前后”表示概数", "families": ["GRAM.NUM"]},
  {"id": "H25-4-095", "level": "4", "page": 319, "cat": "特殊表达法", "sub": "数的表示法", "item": "", "text": "小数、分数、百分数、倍数的表示法", "families": ["GRAM.NUM"]},
  {"id": "H25-5-001", "level": "5", "page": 320, "cat": "语素", "sub": "后缀", "item": "", "text": "—头", "families": ["GRAM.AFFIX"]},
  {"id": "H25-5-002", "level": "5", "page": 320, "cat": "词类", "sub": "代词", "item": "指示代词", "text": "彼此、如此、本", "families": ["GRAM.PRON"]},
  {"id": "H25-5-003", "level": "5", "page": 320, "cat": "词类", "sub": "量词", "item": "名量词", "text": "册、朵、届、颗、匹、行、架、群、支、根、批、束、副、集、周", "families": ["VOC.MEASURE"]},
  {"id": "H25-5-004", "level": "5", "page": 320, "cat": "词类", "sub": "量词", "item": "动量词", "text": "眼", "families": ["VOC.MEASURE"]},
  {"id": "H25-5-005", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "过于、相当、较¹、可²、格外、极其", "families": ["GRAM.ADV"]},
  {"id": "H25-5-006", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "时刻、曾经、立刻、连忙、始终、早已、即将、急忙、渐渐、尽快、早晚", "families": ["GRAM.ADV"]},
  {"id": "H25-5-007", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "老是、通常、时常", "families": ["GRAM.ADV"]},
  {"id": "H25-5-008", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "方式副词", "text": "尽量、亲自", "families": ["GRAM.ADV"]},
  {"id": "H25-5-009", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "关联副词", "text": "便、一旦", "families": ["GRAM.ADV"]},
  {"id": "H25-5-010", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "情态副词", "text": "似乎、仿佛", "families": ["GRAM.ADV"]},
  {"id": "H25-5-011", "level": "5", "page": 320, "cat": "词类", "sub": "副词", "item": "语气副词", "text": "毕竟、居然、反正、根本、果然、简直、绝对、的确、反而、白、刚好、可³", "families": ["GRAM.ADV"]},
  {"id": "H25-5-012", "level": "5", "page": 320, "cat": "词类", "sub": "介词", "item": "引出时间、处所", "text": "自从", "families": ["GRAM.PREP"]},
  {"id": "H25-5-013", "level": "5", "page": 320, "cat": "词类", "sub": "介词", "item": "引出方向、路径", "text": "朝、沿（着）", "families": ["GRAM.PREP"]},
  {"id": "H25-5-014", "level": "5", "page": 320, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "替、同¹、较²", "families": ["GRAM.PREP"]},
  {"id": "H25-5-015", "level": "5", "page": 320, "cat": "词类", "sub": "介词", "item": "引出凭借、依据", "text": "凭", "families": ["GRAM.PREP"]},
  {"id": "H25-5-016", "level": "5", "page": 320, "cat": "词类", "sub": "介词", "item": "引出凭借、依据", "text": "据", "families": ["GRAM.PREP"]},
  {"id": "H25-5-017", "level": "5", "page": 320, "cat": "词类", "sub": "介词", "item": "引出凭借、依据", "text": "依据", "families": ["GRAM.PREP"]},
  {"id": "H25-5-018", "level": "5", "page": 320, "cat": "词类", "sub": "连词", "item": "连接词或词组", "text": "以及、同²", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-019", "level": "5", "page": 320, "cat": "词类", "sub": "连词", "item": "连接分句或句子", "text": "从而、可见、假如、总之", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-5-020", "level": "5", "page": 320, "cat": "词类", "sub": "助词", "item": "其他助词", "text": "似的", "families": ["GRAM.COMPAR"]},
  {"id": "H25-5-021", "level": "5", "page": 320, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "A来A去", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-022", "level": "5", "page": 320, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "A着A着", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-023", "level": "5", "page": 320, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "没A没B", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-024", "level": "5", "page": 320, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "说A就A", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-025", "level": "5", "page": 320, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "不得了", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-026", "level": "5", "page": 320, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "用不着", "families": ["GRAM.COMP", "GRAM.FIXED"]},
  {"id": "H25-5-027", "level": "5", "page": 320, "cat": "固定格式", "sub": "", "item": "", "text": "从……来看", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-5-028", "level": "5", "page": 320, "cat": "固定格式", "sub": "", "item": "", "text": "A的A，B的B", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-029", "level": "5", "page": 320, "cat": "固定格式", "sub": "", "item": "", "text": "（自）……以来", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-5-030", "level": "5", "page": 320, "cat": "固定格式", "sub": "", "item": "", "text": "由……组成", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-5-031", "level": "5", "page": 320, "cat": "固定格式", "sub": "", "item": "", "text": "X也不是，Y也不是", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-032", "level": "5", "page": 320, "cat": "固定格式", "sub": "", "item": "", "text": "X也X不得，Y也Y不得", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-033", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "X是它，Y也是它", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-034", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "X着也是X着", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-035", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "不管怎样说", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-036", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "真有你/他/她的", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-037", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "X什么X", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-5-038", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "什么X不X（的）", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-5-039", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "不X白不X", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-040", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "X来X去，都是/就是……", "families": ["GRAM.FIXED"]},
  {"id": "H25-5-041", "level": "5", "page": 321, "cat": "固定格式", "sub": "", "item": "", "text": "动词+什么（就）是什么", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-5-042", "level": "5", "page": 321, "cat": "句子成分", "sub": "状语", "item": "", "text": "多项状语", "families": ["GRAM.ORDER"]},
  {"id": "H25-5-043", "level": "5", "page": 321, "cat": "句子成分", "sub": "补语", "item": "可能补语2", "text": "动词+得/不得", "families": ["GRAM.COMP"]},
  {"id": "H25-5-044", "level": "5", "page": 321, "cat": "句子成分", "sub": "补语", "item": "程度补语2", "text": "形容词/心理动词+得+不得了", "families": ["GRAM.COMP"]},
  {"id": "H25-5-045", "level": "5", "page": 321, "cat": "句子成分", "sub": "补语", "item": "趋向补语3", "text": "趋向补语的引申用法：表示状态意义：动词/形容词+下来/下去/起来/过来/过去", "families": ["GRAM.COMP"]},
  {"id": "H25-5-046", "level": "5", "page": 321, "cat": "句子成分", "sub": "补语", "item": "状态补语2", "text": "（1）动词/形容词+得+动词短语", "families": ["GRAM.COMP", "GRAM.DE"]},
  {"id": "H25-5-047", "level": "5", "page": 321, "cat": "句子成分", "sub": "补语", "item": "状态补语2", "text": "（2）动词/形容词+得+主谓短语", "families": ["GRAM.COMP", "GRAM.DE"]},
  {"id": "H25-5-048", "level": "5", "page": 321, "cat": "句子成分", "sub": "补语", "item": "状态补语2", "text": "（3）动词/形容词+得+固定短语", "families": ["GRAM.COMP", "GRAM.DE"]},
  {"id": "H25-5-049", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "“有”字句3", "text": "（1）表示存在、具有：主语+有+着+宾语", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-5-050", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "“有”字句3", "text": "（2）表示附着：主语+动词+有+宾语", "families": ["GRAM.SPECIAL"]},
  {"id": "H25-5-051", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句3", "text": "（1）主语+把+宾语+一+动词", "families": ["GRAM.BA"]},
  {"id": "H25-5-052", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句3", "text": "（2）主语+把+宾语1+动词+宾语2", "families": ["GRAM.BA"]},
  {"id": "H25-5-053", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "连动句3", "text": "前后两个动词性词语具有因果、转折、条件关系", "families": ["GRAM.SERIAL"]},
  {"id": "H25-5-054", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句4", "text": "A+形容词+B+数量补语", "families": ["GRAM.COMPAR"]},
  {"id": "H25-5-055", "level": "5", "page": 321, "cat": "句子的类型", "sub": "特殊句型", "item": "被动句3", "text": "主语+被/叫/让+宾语+给+动词+其他成分", "families": ["GRAM.BEI"]},
  {"id": "H25-5-056", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "承接复句", "text": "……，便……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-057", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "选择复句", "text": "或是……，或是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-058", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "一旦……，就……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-059", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "假如……，（就）……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-060", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "万一……，（就）……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-061", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "假设复句", "text": "……，要不然/不然……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-062", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "因果复句", "text": "……，因而……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-063", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "因果复句", "text": "……，可见……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-064", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "让步复句", "text": "哪怕……，也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-065", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "不但不/不但没有……，反而……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-066", "level": "5", "page": 321, "cat": "句子的类型", "sub": "复句", "item": "递进复句", "text": "不是……，还/还是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-067", "level": "5", "page": 322, "cat": "句子的类型", "sub": "复句", "item": "目的复句", "text": "……，为的是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-068", "level": "5", "page": 322, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "没有……就没有……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-069", "level": "5", "page": 322, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "不……不……", "families": ["GRAM.CONJ"]},
  {"id": "H25-5-070", "level": "5", "page": 322, "cat": "句子的类型", "sub": "复句", "item": "紧缩复句", "text": "再……也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-001", "level": "6", "page": 323, "cat": "语素", "sub": "类前缀", "item": "", "text": "超—、多—、反—、无—、亚—、准—", "families": ["GRAM.AFFIX"]},
  {"id": "H25-6-002", "level": "6", "page": 323, "cat": "语素", "sub": "类后缀", "item": "", "text": "—化、—式、—型、—性", "families": ["GRAM.AFFIX"]},
  {"id": "H25-6-003", "level": "6", "page": 323, "cat": "词类", "sub": "代词", "item": "人称代词", "text": "人家", "families": ["GRAM.PRON"]},
  {"id": "H25-6-004", "level": "6", "page": 323, "cat": "词类", "sub": "量词", "item": "名量词", "text": "专用名量词：串、滴、枝、扇、卷¹、卷²", "families": ["VOC.MEASURE"]},
  {"id": "H25-6-005", "level": "6", "page": 323, "cat": "词类", "sub": "量词", "item": "动量词", "text": "番", "families": ["VOC.MEASURE"]},
  {"id": "H25-6-006", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "特、异常、较为", "families": ["GRAM.ADV"]},
  {"id": "H25-6-007", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "范围副词", "text": "净、一同、大都", "families": ["GRAM.ADV"]},
  {"id": "H25-6-008", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "一时、不时、仍旧、依旧、一向", "families": ["GRAM.ADV"]},
  {"id": "H25-6-009", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "一再、再三", "families": ["GRAM.ADV"]},
  {"id": "H25-6-010", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "方式副词", "text": "不禁、赶忙、特地、特意、偷偷", "families": ["GRAM.ADV"]},
  {"id": "H25-6-011", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "否定副词", "text": "未必", "families": ["GRAM.NEG"]},
  {"id": "H25-6-012", "level": "6", "page": 323, "cat": "词类", "sub": "副词", "item": "语气副词", "text": "恰好、倒是、干脆、明明、总算", "families": ["GRAM.ADV"]},
  {"id": "H25-6-013", "level": "6", "page": 323, "cat": "词类", "sub": "介词", "item": "引出时间、处所", "text": "于", "families": ["GRAM.PREP"]},
  {"id": "H25-6-014", "level": "6", "page": 323, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "至于", "families": ["GRAM.PREP"]},
  {"id": "H25-6-015", "level": "6", "page": 323, "cat": "词类", "sub": "介词", "item": "引出目的、原因", "text": "因", "families": ["GRAM.PREP"]},
  {"id": "H25-6-016", "level": "6", "page": 323, "cat": "词类", "sub": "介词", "item": "表示排除", "text": "除", "families": ["GRAM.PREP"]},
  {"id": "H25-6-017", "level": "6", "page": 323, "cat": "词类", "sub": "连词", "item": "连接分句或句子", "text": "不料", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-6-018", "level": "6", "page": 323, "cat": "词类", "sub": "助词", "item": "结构助词", "text": "所", "families": ["GRAM.OTHER"]},
  {"id": "H25-6-019", "level": "6", "page": 323, "cat": "词类", "sub": "助词", "item": "语气助词", "text": "啦、嘛", "families": ["GRAM.PARTICLE"]},
  {"id": "H25-6-020", "level": "6", "page": 323, "cat": "词类", "sub": "助词", "item": "其他助词", "text": "也好", "families": ["GRAM.OTHER"]},
  {"id": "H25-6-021", "level": "6", "page": 323, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "A这A那", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-022", "level": "6", "page": 323, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "左A右B", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-023", "level": "6", "page": 323, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "好（不）容易", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-024", "level": "6", "page": 323, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "那倒（也）是", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-025", "level": "6", "page": 323, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "算了", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-026", "level": "6", "page": 323, "cat": "短语", "sub": "固定短语", "item": "其他", "text": "得了", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-027", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "A一+量词，B一+量词", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-028", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "东一A，西一A", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-029", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "到……为止", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-030", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "X到Y头上来了", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-031", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "不X不……，一X……", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-032", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "好你个X", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-033", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "早（也）不X，晚（也）不X", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-034", "level": "6", "page": 323, "cat": "固定格式", "sub": "", "item": "", "text": "看/瞧+把+宾语（施事）+X得", "families": ["GRAM.FIXED", "GRAM.BA"]},
  {"id": "H25-6-035", "level": "6", "page": 324, "cat": "固定格式", "sub": "", "item": "", "text": "放着X不Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-036", "level": "6", "page": 324, "cat": "固定格式", "sub": "", "item": "", "text": "X了就X了，（没）有……", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-037", "level": "6", "page": 324, "cat": "固定格式", "sub": "", "item": "", "text": "这/那也不X，那/这也不Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-038", "level": "6", "page": 324, "cat": "固定格式", "sub": "", "item": "", "text": "X归X，Y归Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-039", "level": "6", "page": 324, "cat": "固定格式", "sub": "", "item": "", "text": "看你X的/瞧他X的", "families": ["GRAM.FIXED"]},
  {"id": "H25-6-040", "level": "6", "page": 324, "cat": "句子成分", "sub": "补语", "item": "程度补语3", "text": "动词/形容词+透+了", "families": ["GRAM.COMP"]},
  {"id": "H25-6-041", "level": "6", "page": 324, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句4", "text": "（1）主语（非生物体）+把+宾语+动词+其他成分", "families": ["GRAM.BA"]},
  {"id": "H25-6-042", "level": "6", "page": 324, "cat": "句子的类型", "sub": "特殊句型", "item": "“把”字句4", "text": "（2）主语+把+宾语（施事）+动词+其他成分", "families": ["GRAM.BA"]},
  {"id": "H25-6-043", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "并列复句", "text": "一时……一时……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-044", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "选择复句", "text": "要么……，要么……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-045", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "转折复句", "text": "虽……，但/可/却/也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-046", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "凡是……，都……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-047", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "除非……，才……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-048", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "条件复句", "text": "除非……，否则/不然……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-049", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "让步复句", "text": "就算……，也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-6-050", "level": "6", "page": 324, "cat": "句子的类型", "sub": "复句", "item": "目的复句", "text": "……，以便……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-001", "level": "7-9", "page": 325, "cat": "语素", "sub": "类前缀", "item": "", "text": "后—、亲—", "families": ["GRAM.AFFIX"]},
  {"id": "H25-79-002", "level": "7-9", "page": 325, "cat": "语素", "sub": "类后缀", "item": "", "text": "—观、—鬼、—界、—然、—坛、—为、—制", "families": ["GRAM.AFFIX"]},
  {"id": "H25-79-003", "level": "7-9", "page": 325, "cat": "词类", "sub": "动词", "item": "", "text": "巴不得、并非、除外、犯不着、犯得着、恨不得、可否、可谓、免不了、所谓、有所、予以", "families": ["GRAM.OTHER"]},
  {"id": "H25-79-004", "level": "7-9", "page": 325, "cat": "词类", "sub": "代词", "item": "人称代词", "text": "我", "families": ["GRAM.PRON"]},
  {"id": "H25-79-005", "level": "7-9", "page": 325, "cat": "词类", "sub": "代词", "item": "指示代词", "text": "彼、这么着、兹", "families": ["GRAM.PRON"]},
  {"id": "H25-79-006", "level": "7-9", "page": 325, "cat": "词类", "sub": "代词", "item": "疑问代词", "text": "何、怎么着", "families": ["GRAM.QUESTION", "GRAM.PRON"]},
  {"id": "H25-79-007", "level": "7-9", "page": 325, "cat": "词类", "sub": "代词", "item": "数量代词", "text": "若干", "families": ["GRAM.NUM", "GRAM.PRON"]},
  {"id": "H25-79-008", "level": "7-9", "page": 325, "cat": "词类", "sub": "量词", "item": "名量词", "text": "重、截、缕、码、枚、摊、丸、则、幢、宗", "families": ["VOC.MEASURE"]},
  {"id": "H25-79-009", "level": "7-9", "page": 325, "cat": "词类", "sub": "量词", "item": "动量词", "text": "通", "families": ["VOC.MEASURE"]},
  {"id": "H25-79-010", "level": "7-9", "page": 325, "cat": "词类", "sub": "量词", "item": "复合量词", "text": "人次", "families": ["VOC.MEASURE"]},
  {"id": "H25-79-011", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "程度副词", "text": "大为、分外、何等、极度、极力、略、略微、颇、稍稍、万分、微、尤为、愈加、越发", "families": ["GRAM.ADV"]},
  {"id": "H25-79-012", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "范围副词", "text": "大体、概、皆、尽、均、通通、统统、唯、唯独、唯有、无非、一概", "families": ["GRAM.ADV"]},
  {"id": "H25-79-013", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "时间副词", "text": "姑且、即、即时、届时、尽早、就此、历来、尚、随即、向来、一经、暂且、早日", "families": ["GRAM.ADV"]},
  {"id": "H25-79-014", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "频率副词", "text": "连连、屡次、屡屡、频、时而、时时、相继、一个劲（儿）、一连、再度", "families": ["GRAM.ADV"]},
  {"id": "H25-79-015", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "方式副词", "text": "按理、按说、百般、不由得、趁机、趁早、大肆、断然、公然、火速、截然、竭力、尽情、就近、刻意、拼命、强行、任意、日趋、如期、擅自、私自、特此、瞎、一并、一举、一手、毅然、有意、照常、照例、照样、执意、骤然、逐一、专程", "families": ["GRAM.ADV"]},
  {"id": "H25-79-016", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "否定副词", "text": "不见得、绝不、无从、无须、无可、勿", "families": ["GRAM.NEG"]},
  {"id": "H25-79-017", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "语气副词", "text": "必定、必将、不妨、不免、反倒、非得、分明、怪不得、果真、好在、何必、竟、愣、莫非、难怪、宁可、宁愿、碰巧、偏偏、恰巧、切、情愿、势必、索性、万万、未免、务必、幸好、幸亏、终究、何不、何尝、何苦", "families": ["GRAM.ADV"]},
  {"id": "H25-79-018", "level": "7-9", "page": 325, "cat": "词类", "sub": "副词", "item": "判断副词", "text": "乃", "families": ["GRAM.ADV"]},
  {"id": "H25-79-019", "level": "7-9", "page": 325, "cat": "词类", "sub": "介词", "item": "引出时间、处所", "text": "打", "families": ["GRAM.PREP"]},
  {"id": "H25-79-020", "level": "7-9", "page": 325, "cat": "词类", "sub": "介词", "item": "引出对象", "text": "当着、就⁶", "families": ["GRAM.PREP"]},
  {"id": "H25-79-021", "level": "7-9", "page": 325, "cat": "词类", "sub": "介词", "item": "引出凭借、依据", "text": "本着、基于、鉴于¹、经、依", "families": ["GRAM.PREP"]},
  {"id": "H25-79-022", "level": "7-9", "page": 325, "cat": "词类", "sub": "连词", "item": "连接分句或句子", "text": "鉴于²、况且、免得、若、倘若、以防", "families": ["GRAM.CONJ", "DISC.CONNECT"]},
  {"id": "H25-79-023", "level": "7-9", "page": 325, "cat": "词类", "sub": "连词", "item": "连接词或词组以及分句或句子", "text": "加之、乃至、且", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-024", "level": "7-9", "page": 325, "cat": "词类", "sub": "助词", "item": "语气助词", "text": "罢了、也罢、矣", "families": ["GRAM.PARTICLE"]},
  {"id": "H25-79-025", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "爱A不A", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-026", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "半A半B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-027", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "不A不B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-028", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "不A而B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-029", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "东A西B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-030", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "非A非B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-031", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "忽A忽B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-032", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "或A或B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-033", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "可A可B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-034", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "连A带B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-035", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "七A八B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-036", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "时A时B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-037", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "无A不B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-038", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "无A可B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-039", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "四字格", "text": "自A自B", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-040", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "不瞒你说", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-041", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "不是", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-042", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "不是我说你", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-043", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "反过来（说）", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-044", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "概括来说", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-045", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "归根到底", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-046", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "话是这么说", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-047", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "话（又）说回来", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-048", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "换句话说", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-049", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "简（而）言之", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-050", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "可不（是嘛）", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-051", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "老实说", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-052", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "（你）还别说", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-053", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "你看你", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-054", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "说到哪儿去了", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-055", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "说真的", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-056", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "退一步说", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-057", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "无论如何", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-058", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "要（让）我说", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-059", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "这不", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-060", "level": "7-9", "page": 326, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "这样一来", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-061", "level": "7-9", "page": 327, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "真是的", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-062", "level": "7-9", "page": 327, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "综上所述", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-063", "level": "7-9", "page": 327, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "总的来说", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-064", "level": "7-9", "page": 327, "cat": "短语", "sub": "固定短语", "item": "其他（话语标记）", "text": "总而言之", "families": ["GRAM.FIXED", "DISC.CONNECT"]},
  {"id": "H25-79-065", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "X到这个地步/份上", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-066", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "X得要命/要死", "families": ["GRAM.COMP", "GRAM.FIXED"]},
  {"id": "H25-79-067", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "X都不/没X", "families": ["GRAM.NEG", "GRAM.FIXED"]},
  {"id": "H25-79-068", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "X就X个Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-069", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "X了Y，Y了X", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-070", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "X也好，Y也罢", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-071", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "别提（有）多+形容词+了", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-072", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "不亚于……", "families": ["GRAM.COMPAR", "GRAM.FIXED"]},
  {"id": "H25-79-073", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "不知X是/才好", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-074", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "动不动就……", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-075", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "动词+得个……", "families": ["GRAM.COMP", "GRAM.FIXED"]},
  {"id": "H25-79-076", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "动词+个X", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-077", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "该X（就）X，该Y（就）Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-078", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "何至于……", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-079", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "仅次于X", "families": ["GRAM.COMPAR", "GRAM.FIXED"]},
  {"id": "H25-79-080", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "看在X的面子上", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-081", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "没什么+动词+头儿", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-79-082", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "没什么好+动词+的", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-79-083", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "莫过于……", "families": ["GRAM.COMPAR", "GRAM.FIXED"]},
  {"id": "H25-79-084", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "你说你一个X，……", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-085", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "什么A的B的", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-79-086", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "视……而定", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-79-087", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "谈何……", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-088", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "无非/不过/只是……罢了/而已", "families": ["GRAM.FIXED", "GRAM.PARTICLE"]},
  {"id": "H25-79-089", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "想X之所想，急X之所急", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-090", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "向……致以……", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-79-091", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "要X有/没X，要Y有/没Y", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-092", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "因……而……", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-79-093", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "有何X", "families": ["GRAM.FIXED"]},
  {"id": "H25-79-094", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "有什么+动词+头儿", "families": ["GRAM.FIXED", "GRAM.QUESTION"]},
  {"id": "H25-79-095", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "（在）……之余", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-79-096", "level": "7-9", "page": 327, "cat": "固定格式", "sub": "", "item": "", "text": "值此……之际，……", "families": ["GRAM.FIXED", "GRAM.PREP"]},
  {"id": "H25-79-097", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "特殊句型", "item": "比较句5", "text": "A+形容词+于/过+B", "families": ["GRAM.COMPAR"]},
  {"id": "H25-79-098", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "并列复句", "text": "一来……，二来……，三来……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-099", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "并列复句", "text": "一则……，二则……，三则……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-100", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "解说复句", "text": "所谓……，就是……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-101", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "选择复句", "text": "或……，或……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-102", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "选择复句", "text": "宁可/宁愿……，也不……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-103", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "选择复句", "text": "与其……，宁愿/宁可……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-104", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "转折复句", "text": "X（倒）是X（了），……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-105", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "转折复句", "text": "别看……，……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-106", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "转折复句", "text": "虽说……，但/可……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-107", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "条件复句", "text": "无论……与否，都……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-108", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "条件复句", "text": "凡……（者），均（可）……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-109", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "假设复句", "text": "假若/假使……，……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-110", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "假设复句", "text": "幸亏/幸好……，不然/否则……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-111", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "假设复句", "text": "纵然/纵使……，也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-112", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "因果复句", "text": "（因）……，故……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-113", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "因果复句", "text": "……，以至（于）……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-114", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "递进复句", "text": "别说……，都/也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-115", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "递进复句", "text": "……不说，还……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-116", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "递进复句", "text": "连……都……，更不用说……了", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-117", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "递进复句", "text": "……尚且……，（更）何况……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-118", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "递进复句", "text": "……，更不用说……了", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-119", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "目的复句", "text": "为（了）……起见，……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-120", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "目的复句", "text": "……，以……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-121", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "紧缩复句", "text": "非得……才……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-122", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "简单复句", "item": "紧缩复句", "text": "任……也……", "families": ["GRAM.CONJ"]},
  {"id": "H25-79-123", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "多重复句", "item": "", "text": "多重并列复句", "families": ["GRAM.CONJ", "DISC.COHERE"]},
  {"id": "H25-79-124", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "多重复句", "item": "", "text": "多重转折复句", "families": ["GRAM.CONJ", "DISC.COHERE"]},
  {"id": "H25-79-125", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "多重复句", "item": "", "text": "多重假设复句", "families": ["GRAM.CONJ", "DISC.COHERE"]},
  {"id": "H25-79-126", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "多重复句", "item": "", "text": "多重因果复句", "families": ["GRAM.CONJ", "DISC.COHERE"]},
  {"id": "H25-79-127", "level": "7-9", "page": 328, "cat": "句子的类型", "sub": "多重复句", "item": "", "text": "多重递进复句", "families": ["GRAM.CONJ", "DISC.COHERE"]},
  {"id": "H25-79-128", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "时间顺序", "families": ["DISC.COHERE"]},
  {"id": "H25-79-129", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "空间顺序", "families": ["DISC.COHERE"]},
  {"id": "H25-79-130", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "逻辑顺序", "families": ["DISC.COHERE"]},
  {"id": "H25-79-131", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "话题延伸", "families": ["DISC.COHERE"]},
  {"id": "H25-79-132", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "话题转换", "families": ["DISC.COHERE"]},
  {"id": "H25-79-133", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "承前省略", "families": ["DISC.REFER"]},
  {"id": "H25-79-134", "level": "7-9", "page": 328, "cat": "语段（句群）", "sub": "", "item": "", "text": "蒙后省略", "families": ["DISC.REFER"]},
];
